"""Generate AI-powered PDF proposals for businesses."""
from datetime import datetime
from pathlib import Path
from fpdf import FPDF
from .config import PDF_DIR


def generate_proposal_pdf(business: dict, sender_name: str = "The Team") -> str:
    """Generate a professional PDF proposal for a business. Returns file path."""
    name = business.get("name", "Business")
    address = business.get("address", "")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=25)

    # ── Cover page ──
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(25, 118, 210)
    pdf.multi_cell(0, 14, "Website Proposal\n", align="C")
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 10, f"Prepared for {name}\n", align="C")
    pdf.multi_cell(0, 8, f"Date: {datetime.now().strftime('%B %d, %Y')}\n", align="C")
    pdf.multi_cell(0, 8, f"Prepared by: {sender_name}\n", align="C")
    pdf.ln(10)

    # ── Understanding ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(33, 33, 33)
    pdf.multi_cell(0, 10, "Understanding Your Business\n")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    desc = (
        f"We understand that {name} is looking to strengthen its online presence. "
        f"{'Located at ' + address + ', ' if address else ''}"
        f"we see a clear opportunity to showcase what makes you special to potential "
        f"customers who are searching online."
    )
    pdf.multi_cell(0, 7, desc + "\n")

    # ── What we propose ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(33, 33, 33)
    pdf.multi_cell(0, 10, "What We Propose\n")
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(33, 33, 33)
    pdf.multi_cell(0, 8, "Core Features:\n")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    features = [
        "Responsive, mobile-first design that looks great on phones",
        "SEO optimised for local search (Google Maps, local results)",
        "Contact form with instant email notifications",
        "Google Maps integration with directions",
        "Business hours widget that updates automatically",
        "Fast loading - under 2 seconds",
        "Social media links and sharing",
    ]
    for f in features:
        pdf.multi_cell(0, 7, f"  - {f}\n")

    # ── Why you need this ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(33, 33, 33)
    pdf.multi_cell(0, 10, "Why You Need This\n")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    reasons = [
        "76% of people who search nearby visit a business within 24 hours",
        "Businesses with websites get 2x more leads than those without",
        "A professional site builds trust before customers even walk in",
        "You can update info, hours, and specials instantly",
    ]
    for r in reasons:
        pdf.multi_cell(0, 7, f"  - {r}\n")

    # ── Pricing ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(33, 33, 33)
    pdf.multi_cell(0, 10, "Pricing\n")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    tiers = [
        ("Starter - $499", "Single page, contact form, basic SEO"),
        ("Professional - $999", "Multi-page, blog setup, advanced SEO, analytics"),
        ("Premium - $1,999", "E-commerce ready, booking system, priority support"),
    ]
    for tier, desc in tiers:
        pdf.set_font("Helvetica", "B", 11)
        pdf.multi_cell(0, 7, f"  {tier}\n")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 7, f"    {desc}\n")
        pdf.set_text_color(60, 60, 60)

    # ── Next steps ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(33, 33, 33)
    pdf.multi_cell(0, 10, "Next Steps\n")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 60)
    steps = [
        "1. Schedule a quick 15-minute call to discuss your needs",
        "2. We create a free mockup within 48 hours",
        "3. Review, approve, and launch within 7 days",
    ]
    for s in steps:
        pdf.multi_cell(0, 7, f"  {s}\n")

    # ── Footer ──
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 10)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 7, f"Generated by AI on {datetime.now().strftime('%B %d, %Y')}\n", align="C")
    pdf.multi_cell(0, 7, "Let's build something great together!\n", align="C")

    # ── Save ──
    slug = name.replace(" ", "_").replace("'", "").lower()
    filename = f"proposal_{slug}.pdf"
    output_path = PDF_DIR / filename
    pdf.output(str(output_path))
    return str(output_path)
