"""Sent-email receipt PDF.

After an email is sent, render a clean one-page PDF record:
  - business name
  - To / Subject / Body
  - sent timestamp
  - attached proposal PDF name (if any)

Saves under agent_output/pdfs/sent/<business_slug>_<timestamp>.pdf
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from fpdf import FPDF

from .config import PDF_DIR

_SENT_DIR = PDF_DIR / "sent"
_SENT_DIR.mkdir(parents=True, exist_ok=True)


def _slug(name: str) -> str:
    return name.replace(" ", "_").replace("'", "").lower()


def _latin1(text: str) -> str:
    """Make any text safe for fpdf's core Helvetica font (latin-1 only).

    AI-written bodies naturally carry smart quotes, em/en dashes and other
    Unicode punctuation; without this the receipt PDF crashes after the
    email has already gone out, so the UI reports a failure for a real send.
    """
    return (text or "").encode("latin-1", "replace").decode("latin-1")


def sent_dir() -> Path:
    """Directory where sent-email receipt PDFs are written."""
    return _SENT_DIR


def send_receipt_pdf(
    business_name: str,
    to: str,
    subject: str,
    body: str,
    sender_name: str = "The Team",
    attached_pdf_name: str | None = None,
    out_dir: Path | None = None,
) -> str:
    """Render and save a one-page PDF record of a sent email.

    Records: business name, To, From, Subject, Body, attached proposal name,
    and the sent timestamp. Saved under agent_output/pdfs/sent/.
    """
    d = out_dir or _SENT_DIR
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{_slug(business_name)}_{ts}.pdf"
    path = d / filename

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_fill_color(25, 118, 210)
    pdf.rect(0, 0, 210, 34, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_y(9)
    pdf.cell(0, 10, "Email Sent - Record", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_y(22)
    pdf.cell(0, 8, f"Sent: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C")

    y = 44
    pdf.set_text_color(33, 33, 33)

    def section(title: str, value: str, height: int = 8):
        nonlocal y
        pdf.set_xy(20, y)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(34, height, title)
        pdf.set_xy(54, y)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(150, height, value)
        y = pdf.get_y() + 3
        pdf.set_text_color(33, 33, 33)

    section("Business", _latin1(business_name))
    section("To", _latin1(to))
    section("From", _latin1(sender_name))
    section("Subject", _latin1(subject))
    section("Body", _latin1(body), height=6)

    if attached_pdf_name:
        section("Attached proposal", _latin1(attached_pdf_name))

    pdf.set_y(-16)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, f"Generated by J.A.R.V.I.S outreach on {datetime.now().strftime('%Y-%m-%d')}", align="C")
    pdf.output(str(path))
    return str(path)
